# Generated by Django 4.2 on 2024-04-22 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='photo',
            fields=[
                ('photoId', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True, max_length=50)),
                ('image', models.FileField(null=True, upload_to='photo/')),
            ],
        ),
        migrations.CreateModel(
            name='photo_reviews',
            fields=[
                ('photoReviewId', models.AutoField(primary_key=True, serialize=False)),
                ('reivew', models.CharField(max_length=50)),
                ('photoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.photo')),
            ],
        ),
    ]
