# Generated by Django 4.2 on 2024-04-23 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_photoreview_alter_photo_date_alter_photo_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoreview',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.photo'),
        ),
    ]
