# Generated by Django 4.2 on 2024-04-22 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_rename_noteid_note_index_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteReview',
            fields=[
                ('noteReviewId', models.AutoField(primary_key=True, serialize=False)),
                ('review', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='note/images/'),
        ),
        migrations.DeleteModel(
            name='note_reviews',
        ),
        migrations.AddField(
            model_name='notereview',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='note.note'),
        ),
    ]
