# Generated by Django 4.2 on 2024-04-22 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_rename_jobid_job_index_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobReview',
            fields=[
                ('jobReviewId', models.AutoField(primary_key=True, serialize=False)),
                ('review', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='job/images/'),
        ),
        migrations.DeleteModel(
            name='job_reviews',
        ),
        migrations.AddField(
            model_name='jobreview',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='job.job'),
        ),
    ]
