# Generated by Django 4.2 on 2024-04-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_jobreview_alter_job_date_alter_job_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
